name: compile-papyrus-scripts
on: 
  workflow_dispatch:
    inputs:
        version:
          description: 'Which version should be build against? Defaults to latest'
          required: false
          default: '1.8.86.0'

jobs:
    compile-scripts:
        runs-on: windows-latest
        steps: 
            - name: Checkout
              uses: actions/checkout@v4

            # Fetch and extract the tools we need
            - name: Fetch Caprica 0.3.0
              shell: bash
              run: gh release download -O .github/Caprica.7z -p '*.7z' -R Orvid/Caprica v0.3.0
              env:
                GH_TOKEN: ${{ github.token }}
            
            - name: Extract Caprica EXE file
              shell: bash
              run: 7z x .github/Caprica.7z -o.github/Caprica

            - name: Fetch xEdit (to get BSArchPro)
              shell: bash
              run: gh release download -O .github/xEdit.7z -p '*.7z' -R TES5Edit/TES5Edit xedit-4.1.5
              env:
                GH_TOKEN: ${{ github.token }}

            - name: Extract xEdit files
              shell: bash
              run: 7z x .github/xEdit.7z -o.github/xEdit

            # - name: Fetch vanilla scripts
            #   shell: bash
            #   run: |
            #     curl -L -o .github/Scripts.7z -H "key: ${{ secrets.PAPYRUS_KEY }}" "https://starfieldpatch.dev/api/papyrus/get"
            
            # - name: Extract vanilla scripts
            #   shell: bash
            #   run: 7z x .github/Scripts.7z -o.github/Scripts

            # Perform the actions to build a release.
            # - name: Run Caprica
            #   shell: bash
            #   run: .github/Caprica/Caprica.exe --game starfield --import ".github/Scripts" --output "Scripts" "Scripts/source" -R -q

            - name: Create Assets.json for BSArchPro
              uses: actions/github-script@v6
              with:
                script: |
                  const generateAssets = require('./.github/workflows/generateAssets.js')
                  await generateAssets({ github, context })
          
            # - name: Create .bsarch file for BSArchPro (zip the Assets.json)
            #   shell: bash
            #   run: 7z a -tzip .github/SFCP.bsarch .github/assets.json

            - name: Run BSArchPro to create the archive(s)
              shell: bash
              run: .github/xEdit/BSArchPro64.exe .github/SFCP.bsarch
            
            - name: Upload Output
              uses: actions/upload-artifact@v3
              with: 
                name: compiled-scripts
                path: |
                  StarfieldCommunityPatch - Main.ba2