name: tag-github-issues
on: 
  issues:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            sparse-checkout: |
              .github

      - name: Apply tags
        uses: actions/github-script@v6
        with: 
          script: |
            const tagFunc = require('./.github/workflows/tagFunc.js')
            console.log({ context, github })
            tagFunc({ github, context })