name: tag-github-issues
on: 
  issues:
    types: [opened]

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with: 
          script: |
            const tagFunc = require('./tagFunc.js')
            console.log({ context, github })
            tagFunc({ github, context })